name: Repository Build Workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - 'main'

jobs:
  tartufo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Checkout GoDaddy Actions repo. # Checkout shared actions repository gd-actions
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: gdcorp-actions/tartufo
          token: ${{ secrets.REPO_CLONE_TOKEN }} # PAT with read access to gdcorp-cp/gd-actions
          ref: v2.1.0 # https://godaddy.slack.com/archives/C011GSS1CES/p1617653572031100
          path: tartufo # Relative to github working directory
          persist-credentials: false
      - name: Run Tartufo Scan.
        uses: ./tartufo # Relative reference to action in gd-actions repository
        with:
          github_token: ${{ secrets.REPO_CLONE_TOKEN }}

  unit-test:
    needs: tartufo-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Set up Python 3.8
        uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          make test

  app-validate:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Validate the app
        run: |
          make validate
